version: "3.9"
services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build:
      context: ./server
    container_name: server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - "9000:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"